// Generated by scripts/blog.ts from src/content/blog/*.md. Do not edit.
import type { PostMeta } from "./types";

/** Every published post, newest first. */
export const POSTS: PostMeta[] = [
  {
    "slug": "paginate-text-by-measuring-type",
    "title": "How to paginate text by measuring type, not guessing",
    "description": "How Atlas cuts a long story into magazine columns that never overflow, by binary-searching word counts against real type in the browser.",
    "kind": "engineering",
    "date": "2026-10-01",
    "tags": [
      "typography",
      "pagination",
      "web layout"
    ],
    "keyword": "paginate text by measuring type",
    "feature": "0.1.0",
    "minutes": 12
  }
];

/** Each post's rendered HTML, a chunk of its own so only the post being read is fetched. */
export const BODIES: Record<string, () => Promise<{ default: string }>> = {
  "paginate-text-by-measuring-type": () => import("./bodies/paginate-text-by-measuring-type"),
};
